version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: false
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build:
  project: CertPinner.sln
  verbosity: minimal
